use anyhow::Result;
use nftables::{batch::Batch, schema, types};
use rkl::network::receiver::NetworkReceiver;
use std::process::Command;
use nix::unistd::geteuid;

fn is_root() -> bool {
    geteuid().is_root()
}

fn has_nft_command() -> bool {
    Command::new("nft").arg("--version").output().is_ok()
}

#[tokio::test]
async fn test_apply_nft_rules_integration() -> Result<()> {
    // 1. Setup NetworkReceiver with dummy data
    let receiver = NetworkReceiver::new(
        "/tmp/subnet.env".to_string(),
        1,
        "host-gw".to_string(),
        "test-node".to_string(),
    );

    // 2. Generate a simple valid nftables JSON
    let mut batch = Batch::new();
    batch.add(schema::NfListObject::Table(schema::Table {
        family: types::NfFamily::IP,
        name: "rk8s_test".into(),
        ..Default::default()
    }));
    batch.add(schema::NfListObject::Chain(schema::Chain {
        family: types::NfFamily::IP,
        table: "rk8s_test".into(),
        name: "test_chain".into(),
        ..Default::default()
    }));

    let nftables = batch.to_nftables();
    let json_rules = serde_json::to_string(&nftables)?;

    // 3. Call apply_nft_rules
    let result = receiver.apply_nft_rules(json_rules).await;

    // 4. Verify result based on environment
    if is_root() && has_nft_command() {
        assert!(result.is_ok(), "Should succeed when running as root with nft installed");
        
        // Cleanup
        let _ = Command::new("nft").args(&["delete", "table", "ip", "rk8s_test"]).output();
    } else {
        // If not root or no nft, it might fail, but we want to ensure it failed 
        // at the application step, not parsing.
        // The error message from nftables crate usually contains "nft execution failed" or similar.
        if let Err(e) = result {
            println!("Apply failed as expected (non-root/no-nft): {}", e);
            // We consider this a pass for the logic flow test
        } else {
            // It might succeed if using a mock backend or if nftables crate handles dry-run? 
            // Unlikely to succeed without privs.
            println!("Apply succeeded unexpectedly (maybe dry run?)");
        }
    }

    Ok(())
}

#[tokio::test]
async fn test_apply_nft_rules_invalid_json() {
    let receiver = NetworkReceiver::new(
        "/tmp/subnet.env".to_string(),
        1,
        "host-gw".to_string(),
        "test-node".to_string(),
    );

    let invalid_json = "{ invalid json }";
    let result = receiver.apply_nft_rules(invalid_json.to_string()).await;

    assert!(result.is_err());
    let err = result.unwrap_err();
    println!("Error message: {}", err);
    // The error comes from serde_json parsing
    assert!(err.to_string().contains("key must be a string") || err.to_string().contains("JSON") || err.to_string().contains("syntax"));
}

#[tokio::test]
async fn test_apply_complex_rks_rules() -> Result<()> {
    // This test simulates the complex rules generated by RKS to ensure RKL can handle them.
    // It constructs a batch with Maps, Sets, Jumps, and DNAT.

    let receiver = NetworkReceiver::new(
        "/tmp/subnet.env".to_string(),
        1,
        "host-gw".to_string(),
        "test-node".to_string(),
    );

    use nftables::{expr, stmt};

    let mut batch = Batch::new();
    
    // Table
    batch.add(schema::NfListObject::Table(schema::Table {
        family: types::NfFamily::IP,
        name: "rk8s_complex_test".into(),
        ..Default::default()
    }));

    // Chain: services
    batch.add(schema::NfListObject::Chain(schema::Chain {
        family: types::NfFamily::IP,
        table: "rk8s_complex_test".into(),
        name: "services".into(),
        ..Default::default()
    }));

    // Chain: svc-test
    batch.add(schema::NfListObject::Chain(schema::Chain {
        family: types::NfFamily::IP,
        table: "rk8s_complex_test".into(),
        name: "svc-test".into(),
        ..Default::default()
    }));

    // Rule: Jump to svc-test
    batch.add(schema::NfListObject::Rule(schema::Rule {
        family: types::NfFamily::IP,
        table: "rk8s_complex_test".into(),
        chain: "services".into(),
        expr: std::borrow::Cow::Owned(vec![
            stmt::Statement::Match(stmt::Match {
                left: expr::Expression::Named(expr::NamedExpression::Payload(expr::Payload::PayloadField(expr::PayloadField {
                    protocol: "ip".into(),
                    field: "daddr".into(),
                }))),
                right: expr::Expression::String("10.96.0.100".into()),
                op: stmt::Operator::EQ,
            }),
            stmt::Statement::Goto(stmt::JumpTarget { target: "svc-test".into() })
        ]),
        ..Default::default()
    }));

    // Rule: DNAT with Numgen and Map (Load Balancing)
    let map_data = vec![
        expr::SetItem::Mapping(
            expr::Expression::Number(0),
            expr::Expression::String("10.244.1.2".into())
        ),
        expr::SetItem::Mapping(
            expr::Expression::Number(1),
            expr::Expression::String("10.244.1.3".into())
        ),
    ];

    let numgen_expr = expr::Expression::Named(expr::NamedExpression::Numgen(expr::Numgen {
        mode: expr::NgMode::Random,
        ng_mod: 2,
        offset: None,
    }));

    let map_expr = expr::Expression::Named(expr::NamedExpression::Map(Box::new(expr::Map {
        key: numgen_expr,
        data: expr::Expression::Named(expr::NamedExpression::Set(map_data)),
    })));

    let dnat_stmt = stmt::Statement::DNAT(Some(stmt::NAT {
        addr: Some(map_expr),
        family: Some(stmt::NATFamily::IP),
        port: Some(expr::Expression::Number(8080)),
        flags: None,
    }));

    batch.add(schema::NfListObject::Rule(schema::Rule {
        family: types::NfFamily::IP,
        table: "rk8s_complex_test".into(),
        chain: "svc-test".into(),
        expr: std::borrow::Cow::Owned(vec![dnat_stmt]),
        ..Default::default()
    }));

    let nftables = batch.to_nftables();
    let json_rules = serde_json::to_string(&nftables)?;

    // Apply
    let result = receiver.apply_nft_rules(json_rules).await;

    if is_root() && has_nft_command() {
        assert!(result.is_ok(), "Should succeed applying complex rules as root");
        let _ = Command::new("nft").args(&["delete", "table", "ip", "rk8s_complex_test"]).output();
    } else {
        if let Err(e) = result {
            println!("Complex apply failed as expected (non-root): {}", e);
            // Ensure it's not a parsing error
            assert!(!e.to_string().contains("JSON") && !e.to_string().contains("syntax"));
        }
    }

    Ok(())
}
